apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam:892958774317:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::892958774317:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4S7RBZ11OLR9
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-16T21:04:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5010"
  uid: 296b35b6-b75b-4616-bd06-4fdba716ba09
